### ISSUE TITLE
Hold uden timer vises i fraværsoversigten

### ISSUE THREAD

**Issue by rkarmark** [BetterLectio/betterLectio#103]
Se følgende billede:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/17333987/211912801-e1a05958-29cd-424f-afe9-4c5cc1942f82.png">

Hold hvor at der ikke har været moduler/ikke har været moduler som var obligatoriske timer vises stadigt i fraværsoversigten.

Problemet eksistere både i production og i dev branch.

Jeg kan godt komme med mere info hvis i gerne vil have det.

**Comment by dnorhoj** [comment]
Er det et problem dog? Det vises også i lectios fraværs side.

**Comment by rkarmark** [comment]
Jeg skrev issuet, da de prøver kun at vise de hold med fravær. ("Hold uden fravær er ikke vist"). Men jeg tror at have hold hvor at der ikke er nogle timer med mødepligt er smuttet igennem dette.

**Comment by victorDigital** [comment]
det er fikset
