### ISSUE TITLE
Meget høj præcision til karaktergennemsnit

### ISSUE THREAD

**Issue by rkarmark** [BetterLectio/betterLectio#110]
Hvis ens karaktergennemsnit er et irrationelt tal, så viser den på karaktersiden ens karaktere med 14 betydende cifre.

Her er et billede (har ændret karakteren med inspect men længden er den samme, for at vise problemet)
<img width="357" alt="image" src="https://user-images.githubusercontent.com/17333987/212669917-28f45610-614c-4b74-9264-d464665a8340.png">

**Comment by jona799t** [comment]
Nu afrunder den til 2 decimaler. Så snart vi merger dev til main vil ændringerne gå live
