### ISSUE TITLE
cirkel diagrammet forsvinder hvis man trykker på pilen på fravær siden 

### ISSUE THREAD

**Issue by victorDigital** [BetterLectio/betterLectio#144]
cirkel diagrammet forsvinder hvis man trykker på pilen.

_Originally posted by @victorDigital in https://github.com/BetterLectio/betterLectio/issues/140#issuecomment-1436954049_

**Comment by victorDigital** [comment]
![image](https://user-images.githubusercontent.com/99267380/220112466-694de82a-afa4-4d78-b531-cd748c820b99.png)
![image](https://user-images.githubusercontent.com/99267380/220112521-41983b66-aa46-4282-8911-f04b2a47598d.png)

**Comment by JohnnyJTH** [comment]
Det kan jeg ikke reproducere... Hverken på mobil eller pc
