### ISSUE TITLE
lektietab ødelægger de andre tabs, samt sin egen

### ISSUE THREAD

**Issue by CralJuicer** [BetterLectio/betterLectio#147]
**Describe the bug**
Det er ikke muligt at se sine lektier når man trykker på lektieheaderen. Og derefter når man trykker på andre tabs så som opgaver, fravær osv, så displayer de ikke. Der er kun en sort skærm

**To Reproduce**

1. tryk på Lektier
2. Tryk på opgaver/Skema/fravær derefter

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [Chrome]

**Comment by victorDigital** [comment]
@CralJuicer Det har jeg godt selv oplevet, der er noget formatering på en af dine lektier, det er lidt mærkeligt men det burde snart blive fikset.

**Comment by victorDigital** [comment]
burde være fikset for et par uger siden
