### ISSUE TITLE
Scroll-bar virker ikke ordentligt

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#148]
Scroll-baren virker ikke rigtigt. Det ser ud til, at der er to scroll-barer, og at en af dem er statisk. Den anden scroll-bar er kun synlig, når man scroller ned nederst på siden.

Gå til 'https://app.betterlectio.dk/', og fejlen er tydelig. Fejlen findes overalt på siden. På dokumenter (hvor jeg ikke kan scrolle) er den store scrollbar der stadig, selvom jeg ikke kan scrolle.

Fejlen findes på Chrome og Brave. Den findes højst sandsynligt på alle browsere, men den er kun blevet testet på Brave på en computer og på Chrome på en anden.

**Comment by victorDigital** [comment]
i call cap

**Comment by victorDigital** [comment]
det ser ikke ud til andre oplever denne bug, jeg lukker derfor issuet
