### ISSUE TITLE
Skema på mobil indlæser forkert.

### ISSUE THREAD

**Issue by jona799t** [BetterLectio/betterLectio#154]
**Beskriv fejlen**
Når man går en dag frem på skemaet, indlæser BetterLectio dagsnoter og skema fra næste uge. Forekommer kun når man har mobil view.

**For at genskabe**
Trin til at genskabe adfærden:
1. Gå til https://dev--betlec.netlify.app/ på din mobil
2. Åben dit skema
3. Gå en dag frem, og observer at dagsnoten er for næste uge og at BetterLectio laver en http request for skemaet i næste uge.

**Forventet adfærd**
Skemaet indlæser kun næste uge hvis man prøver at indlæse næste mandag.

**Skærmbilleder**
![image](https://user-images.githubusercontent.com/70392256/236671969-e8f19ac4-294f-4bb1-9b8e-659816979df8.png)
Som man kan se på billedet indlæser den uge 20 (mandag 15. – søndag 21. maj 2023), selvom jeg ser på tirsdag den 9. maj.

**Comment by victorDigital** [comment]
@jona799t tænker det er fikset i dev?

**Comment by jona799t** [comment]
Jo det er den
