### ISSUE TITLE
Holdoversætter og line wrap UI bug på mobil

### ISSUE THREAD

**Issue by victorDigital** [BetterLectio/betterLectio#189]
![Screenshot_20230904-195300.png](https://github.com/BetterLectio/betterLectio/assets/99267380/32f541fa-8783-4f9c-a1b9-8537fcbc391b)

**Comment by jona799t** [comment]
Holdoversætteren skal fikses på vores backend. 
https://github.com/BetterLectio/python-lectio/issues/11
