### ISSUE TITLE
Afleveringer

### ISSUE THREAD

**Issue by Sommer420** [BetterLectio/betterLectio#272]
Lige nu kan man se afleveringer for alle år.
Det ville være dejligt, hvis man kun kunne se for indeværende skoleår, ligesom på Lectio.

**Comment by victorDigital** [comment]
enig, det er på listen :)

**Comment by victorDigital** [comment]
![image](https://github.com/user-attachments/assets/22c567e4-31af-49ef-a8b9-660241d6348c)
set denne indstilling i indstillinger
