### ISSUE TITLE
Skemanoter mangler D-:<

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#32]
https://betlec.netlify.app/skema

For det første:
Der mangler stort forbogstav (der er blevet skrevet all-day i stedet for All-day)

For det ANDET!!!!!!!!:
Der skal stå "All day:" i stedet for "All-day"

For det TREEEEEDJJJJJEEEEEEEEEE
Skemanoterne virker ikke >:-( >:-( >:-( >:-(

Tak fordi i lyttede, hav en god dag 😊 
![image](https://user-images.githubusercontent.com/80312590/205645734-011d962e-a99b-451a-873e-c85c54b59a78.png)

**Comment by victorDigital** [comment]
working on it, will get back to you soon!
