### ISSUE TITLE
Mulighed for at lave et custom theme

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#39]
Kunne det lade sig gøre? I kan eventuelt uddelegere opgaven til mig, så vil jeg tilbagevende med et færdigt produkt om 2-3 forretningsår

**Comment by Asguho** [comment]
til at starte med kan du jo lave nogle custom themes og smide dem i en pull request

**Comment by jona799t** [comment]
Det er teknisk set allerede muligt at lave custom themes. Du skal bare skrive dem ind i [tailwind.config.cjs](https://github.com/BetterLectio/betterLectio/blob/main/tailwind.config.cjs)
Du kan finde en theme generator her: https://daisyui.com/theme-generator/

**Comment by JohnnyJTH** [comment]
Han mener nok på frontend...

**Comment by victorDigital** [comment]
@sublollipp det er muligt at gøre det i dev serveren (https://dev--betlec.netlify.app/)
![image](https://user-images.githubusercontent.com/99267380/235501783-f9d434df-9ed4-48c7-878f-5036b581df11.png)
![image](https://user-images.githubusercontent.com/99267380/235502108-a91798c4-a723-4c98-bb09-5bbf4a8c8b82.png)
