### ISSUE TITLE
Sortering af fraværsfag

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#40]
Det ville sådan set bare være ret fedt, hvis man kunne sortere fagene afhængig af hvor mange lektioner man har misset, og hvor mange procent af lektionerne man har misset. (Både fra mindste til højeste og højeste til mindste).

Det var sådan set det. Hav en god dag og start på oprettelsesgebyr i sommerferien, så de nye 1.G'ere (og alle fremtidige 1.G'ere) kan give jer penge. Sælg det til lectio for 450.000 kr. når i går ud og giv alle pengene til mig :D

**Comment by JohnnyJTH** [comment]
Virker nu, https://betterlectio.dk/fravær.

**Comment by victorDigital** [comment]
Done :)
