### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#43]
På windows 11, chrome:
Når jeg åbner betterlectio (betlec.netlify.app), kommer følgende fejlbesked frem: 
"Error fetching data from https://better-lectio-flask-backend.vercel.app/mig"
![image](https://user-images.githubusercontent.com/80312590/205700308-854e843d-657a-406b-827e-0bb1bd116061.png)

**Comment by JohnnyJTH** [comment]
Det er ved at blive fikset, lige nu er du nødt til at logge ud og ind igen.

**Comment by jona799t** [comment]
Det burde være fikset nu.
