### ISSUE TITLE
Knapperne som linker til Lectio linker kun til H.C. Ørsted Gymnasiet - Lyngby

### ISSUE THREAD

**Issue by Mojjedrengen** [BetterLectio/betterLectio#52]
Knappen under dokumenter kun til Lectio til H.C. Ørsted Gymnasiet - Lyngby Og ikke det gymnasium jeg går på.

![billede](https://user-images.githubusercontent.com/99266094/206669864-7a3b877b-d087-4b2d-880d-2ea389984114.png)
![billede](https://user-images.githubusercontent.com/99266094/206669883-4adaf225-e59b-4bd2-83b6-d127057f8407.png)

**Comment by victorDigital** [comment]
haha, den fikser jeg lige 🚀

**Comment by victorDigital** [comment]
og tak for billedet 👌

**Comment by victorDigital** [comment]
fixed as of #55
