### ISSUE TITLE
Engelsk???

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#58]
Der står "Today" i stedet for "I dag" i elementet øverst til højre over skemaet på [https://betterlectio.dk/skema/](https://betterlectio.dk/skema/)
![image](https://user-images.githubusercontent.com/80312590/207304104-bbf586ee-373f-4b3d-94a5-1082f3c8bec9.png)

**Comment by jona799t** [comment]
Det er fikset i dev versionen nu.
