### ISSUE TITLE
Jeg kan ikke fravælge sortering af opgaver

### ISSUE THREAD

**Issue by sublollipp** [BetterLectio/betterLectio#60]
Inde på [https://betterlectio.dk/opgaver](https://betterlectio.dk/opgaver) kan man ikke fravælge sortering mellem afleverede og ikke-afleverede opgaver. Ved ikke om det er en bug eller en fravalgt feature. Jeg synes bare, at det er lidt mærkeligt.

![image](https://user-images.githubusercontent.com/80312590/207985231-dee0ac8e-366c-45c3-97cd-1f251f01c795.png)

**Comment by victorDigital** [comment]
vi er i gang med nogle endringer inde på dev, forvænt et fiks snart

**Comment by jona799t** [comment]
Det er fikset i dev branchen. Du kan tilgå den her: https://dev--betlec.netlify.app

**Comment by victorDigital** [comment]
er fikset i #63
