### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by Mojjedrengen** [BetterLectio/betterLectio#90]
Når jeg logger ind så siger den at der er sket en fejl med at hente data. Det kunne muligvis være på grund af at jeg gå på et andet gymnasium.
![billede](https://user-images.githubusercontent.com/99266094/210744830-c8981787-01e9-48f9-a24e-d18b8772aafe.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 108.0.1

**Comment by Asguho** [comment]
jeg får nogle gange samme error, og min cookie er valid
![billede](https://user-images.githubusercontent.com/78410939/210757030-1086f7cf-bfe0-4de3-985e-59a761ad08aa.png)

**Comment by victorDigital** [comment]
Det skete vidst for alle
tror måske jeg at det er fiket nu i #91

**Comment by Asguho** [comment]
Jeg tror det fikset nu, vi har lige merged til main.
@Mojjedrengen  kan du reproducere fejlen nu?

**Comment by Mojjedrengen** [comment]
Stadig væk fejl
![billede](https://user-images.githubusercontent.com/99266094/210768265-a21ea68a-4269-41b3-bfba-84959b1caca2.png)
![billede](https://user-images.githubusercontent.com/99266094/210768326-a0240cd1-1b71-43b9-9e4d-472da60aed41.png)

**Comment by jona799t** [comment]
Kan du sende et screenshot af hvordan din forside ser ud på den rigtige lectio?

**Comment by Mojjedrengen** [comment]
Jeg syntes at det så merkeligt ud at den popede op med en besked om at der var en fejl med at få data.
![billede](https://user-images.githubusercontent.com/99266094/210808136-2b562a59-ba18-454e-8371-972816822702.png)
![billede](https://user-images.githubusercontent.com/99266094/210808256-c99beb0c-7c75-413b-b356-27faba6ef6b1.png)

**Comment by jona799t** [comment]
Virker det nu?

**Comment by Mojjedrengen** [comment]
Det virker nu
