### ISSUE TITLE
Vi bruger en dårlig måde til at finde ud af om fetch er cached eller ej.

### ISSUE THREAD

**Issue by jona799t** [BetterLectio/betterLectio#99]
Lige nu bruger vi tid det tager at fetch i ms til at finde ud af om noget er cached eller ej. Dette kan skabe problemer for rigtig hurtige forbindelser eller for langsomme computere/telefoner.
Et alternativ kunne være https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize da transferSize er lig med 0 hvis den er cached men det er ikke understøttet på safari endnu.

**Comment by Asguho** [comment]
hvor er det vi laver tjekket?

**Comment by victorDigital** [comment]
[// http.js ](https://github.com/BetterLectio/betterLectio/blob/da4dbbf65a345dbc3f05e3cf3d2f233d38e17e67/src/lib/js/http.js#L45-L71)

**Comment by jona799t** [comment]
Det ser ud til at transferSize nu er understøttet på Safari
![image](https://github.com/BetterLectio/betterLectio/assets/70392256/e62791cc-260a-4035-a66b-85f1765bd8df)
